### ISSUE TITLE
Dynamic UnityEvent argument (stable version)

### ISSUE THREAD

**Issue by 4quet** [DanielEverland/ScriptableObject-Architecture#93] opened 2019-10-13 20:57 UTC
Hello,

I saw issue #92 mentioning that the UnityEvent dynamic parameter is not working anymore.
I'm using the last stable version of Unity (2019.2.9f1) and the bug is also there.

I created an empty project and tested the _BoolGameEventListener_ to be sure there wasn't anything interfering but the problem persists:

![Screen](https://user-images.githubusercontent.com/11979391/66722233-7cf51c00-ee0b-11e9-8cc2-5be59f9657c1.png)

Thanks for this amazing tool !

**Comment by DanielEverland** [comment] 2019-10-15 12:37
Thanks for re-opening the issue. I'll take a look at it asap :)

**Comment by DanielEverland** [comment] 2019-10-19 21:31
I've verified this is a bug with the new version of Unity, it's reproduced if the SerializedProperty used for the typed UnityEvent is sourced from a base class that specifies its type using generic arguments.

Since it's so engrained in the structure of SO-A, I'm afraid there's no simply workaround. You could create your own hard-coded game event listener for every class as a temporary workaround, or simply use a version < 2019.2.

Thanks for the report, I've obviously sent a thorough bug report to Unity. Feel free to leave a comment if you're interested in their reply, if not, I'll just close this issue and hope Unity fixes it asap :)

**Closed by DanielEverland** 2019-10-19 21:31 UTC
Labels: bug

**Comment by DanielEverland** [comment] 2019-10-23 10:07
It's being tracked here: https://issuetracker.unity3d.com/issues/unityevent-drawer-does-not-handle-generic-event-parameters-correctly-when-the-class-is-derived-from-another-class
