### ISSUE TITLE
Value assignment via Editor script

### ISSUE THREAD

**Issue by SiarheiPilat** [DanielEverland/ScriptableObject-Architecture#137] opened 2020-10-06 10:53 UTC
Consider the following scenario. We have two files in the 'Assets' folder: testgovariable.asset (a ScriptableObject of type GameObjectVariable) and a GameObject prefab test.prefab. Consider the following class:

```csharp
public class TestClass : MonoBehaviour
{
    public GameObjectReference TestGoReference;
    public GameObject TestGo;
}
```

We can assign GameObject value via an Editor script like so:

```csharp
Selection.transforms[0].gameObject.GetComponent<TestClass>().TestGo =
(GameObject)AssetDatabase.LoadAssetAtPath("Assets/test.prefab", typeof(GameObject));
```
This works for GameObject, but not for GameObjectReference.Value, when we try the following:

```csharp
Selection.transforms[0].gameObject.GetComponent<TestClass>().TestGoReference.Value =
(GameObjectVariable)AssetDatabase.LoadAssetAtPath("Assets/testgovariable.asset", typeof(GameObjectVariable));
```
Instead, what happens is the GameObjectReference field in the Inspector is switched from "Use Variable" to "Use Constant", while GameObjectReference.Value is 'Null'.

What would be a proper way of assigning the GameObjectReference.Value to a scriptable object via an Editor script?

**Comment by tuleky** [comment] 2020-11-27 09:01
I also have the same problem, I'm not using any editor thing at all, all I want to do is be able to make gameObjectReference null in code. You can do that with gameObjectVariable and set its baseValue I think... but can't do with references.

**Comment by DanielEverland** [comment] 2021-07-15 15:32
This is caused because the property Value relates to the actual GameObject that's being referenced, rather than the Variable you're attempting to assign. Variables can be implicitly converted to the types they represent, so I suspect the following is what happens:

1. A GameObjectVariable is assigned to the property Value, which expects a type of GameObject
2. An implicit conversion is performed, returning the value of your variable. In your case, it seems like the variable's value hasn't been set, and is therefore null
3. Since the Reference doesn't have a variable assigned, it switches to constant mode and assigns the value returned in Step 2 (null).

While there's no way for me to let you assign a Reference to the Value property, I've added a new property called Variable. I also recreated your setup and confirmed that it works.

Thanks for the report! :)

**Closed by DanielEverland** 2021-07-15 15:32 UTC
